'use client'

import { useMemo, useState } from 'react'
import type { ChangeEvent, ReactNode } from 'react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowRight, BarChart3, CalendarDays, Check, Clock3, ImagePlus, Leaf, MapPin, PackageCheck, Plus, Search, SlidersHorizontal, Truck, Users, Utensils, X } from 'lucide-react'

const navItems = [
  { label: 'Dashboard', icon: BarChart3 },
  { label: 'Donate Food', icon: Utensils },
  { label: 'Available Food', icon: PackageCheck },
  { label: 'Pickups', icon: Truck },
  { label: 'Impact', icon: Leaf },
]
const foods = [
  { title: 'Vegetable Biryani & Raita', source: 'Spice Route Kitchen · Restaurant', servings: '120', distance: '1.2 km', time: '1h 14m left', category: 'Vegetarian', score: 92, level: 'Critical' },
  { title: 'Assorted Breads & Croissants', source: 'Maison Boulangerie · Bakery', servings: '60', distance: '2.8 km', time: '2h 48m left', category: 'Bakery', score: 78, level: 'Urgent' },
  { title: 'Conference Lunch Boxes', source: 'Meridian Convention Centre · Event organizer', servings: '240', distance: '4.5 km', time: '46m left', category: 'Non-vegetarian', score: 95, level: 'Critical' },
  { title: 'Fresh Produce Crates', source: 'GreenLeaf Grocers · Grocery', servings: '90', distance: '3.1 km', time: '7h 0m left', category: 'Fruits & vegetables', score: 64, level: 'Moderate' },
  { title: 'Vegan Buddha Bowls', source: 'Rooted Cafe · Cafe', servings: '45', distance: '0.8 km', time: '1h 36m left', category: 'Vegan', score: 81, level: 'Urgent' },
  { title: 'Canteen Dal, Rice & Sabzi', source: 'Northbridge Tech Canteen · Canteen', servings: '180', distance: '6.2 km', time: '3h 30m left', category: 'Vegetarian', score: 73, level: 'Moderate' },
]
const activity = [['Community Kitchen Trust confirmed pickup of 120 servings from Spice Route Kitchen', '8 min ago', 'green'], ['Meridian Convention Centre listed 240 conference lunch boxes', '26 min ago', 'amber'], ['Pickup completed — 180 meals delivered to Community Kitchen Trust', '1 hr ago', 'green'], ['Rooted Cafe listed 45 vegan buddha bowls', '2 hr ago', 'amber'], ["Asha Children's Shelter updated capacity to 120 meals", '3 hr ago', 'amber']]
const chartData = [{ month: 'Apr', meals: 1800 }, { month: 'May', meals: 2250 }, { month: 'Jun', meals: 2050 }, { month: 'Jul', meals: 2900 }, { month: 'Aug', meals: 3300 }, { month: 'Sep', meals: 4000 }]

export default function Page() {
  const [active, setActive] = useState('Dashboard')
  const [toast, setToast] = useState('')
  const [search, setSearch] = useState('')
  const [pickupTab, setPickupTab] = useState('Pending')
  const [donation, setDonation] = useState({ name: 'Vegetable Biryani & Raita', quantity: '18 kg', servings: '120', type: 'Vegetarian', prepared: '11:30', until: '16:30', location: '42 Linking Road, Bandra West', notes: 'Cooked at 11:30, held hot. Trays included, please return.' })
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2800) }
  return <div className="foodloop-app min-h-screen bg-[#f7fbf8] text-[#10271b]">
    <Sidebar active={active} onSelect={setActive} />
    <main className="lg:ml-[200px]"><div className="mx-auto max-w-[930px] px-5 py-7 md:px-8 md:py-8">
      {active === 'Dashboard' && <Dashboard onDonate={() => setActive('Donate Food')} />}
      {active === 'Donate Food' && <DonateFood donation={donation} setDonation={setDonation} onAnalyze={() => notify('Food analyzed. Best matches are ready.')} />}
      {active === 'Available Food' && <AvailableFood search={search} setSearch={setSearch} onClaim={() => notify('Listing claimed. Pickup added to your queue.')} />}
      {active === 'Pickups' && <Pickups tab={pickupTab} setTab={setPickupTab} onConfirm={() => notify('Pickup confirmed successfully.')} />}
      {active === 'Impact' && <Impact />}
    </div></main>
    {toast && <div role="status" className="fixed bottom-5 right-5 z-50 rounded-xl bg-[#10271b] px-4 py-3 text-sm font-medium text-white shadow-lg">{toast}</div>}
  </div>
}

function Sidebar({ active, onSelect }: { active: string; onSelect: (label: string) => void }) { return <aside className="foodloop-sidebar fixed inset-y-0 left-0 z-30 flex w-[220px] flex-col border-r border-[#d8e3dc] bg-white lg:flex"><div className="flex h-[68px] items-center gap-2 px-4"><div className="flex size-8 items-center justify-center rounded-full bg-[#008f5a] text-white"><Leaf className="size-4" /></div><div className="text-[16px] font-medium tracking-[-0.04em]">FoodLoop AI</div></div><nav className="flex flex-1 flex-col gap-1 px-3 pt-1">{navItems.map(({ label, icon: Icon }) => <button key={label} onClick={() => onSelect(label)} className={`flex items-center gap-3 rounded-full px-3 py-2.5 text-left text-[13px] font-medium transition ${active === label ? 'bg-[#e3f3ed] text-[#008f5a]' : 'text-[#61766a] hover:bg-[#f2f7f3]'}`}><Icon className="size-4" />{label}</button>)}</nav><RescueGoal /></aside> }
function RescueGoal() { return <div className="m-1 rounded-2xl bg-[#e9f6f1] p-3"><div className="mb-1 text-[13px] font-medium">Rescue goal</div><p className="mb-2 text-[12px] leading-4 text-[#668073]">24,680 of 30,000 meals this year</p><div className="h-1.5 rounded-full bg-[#c6e6d9]"><div className="h-1.5 w-[82%] rounded-full bg-[#008f5a]" /></div></div> }
function Header({ title, subtitle, action }: { title: string; subtitle: string; action?: ReactNode }) { return <section className="mb-7 flex items-end justify-between gap-5"><div><h1 className="text-[28px] font-medium tracking-[-0.06em] md:text-[30px]">{title}</h1><p className="mt-1 text-[13px] text-[#718579]">{subtitle}</p></div>{action}</section> }
function Stat({ icon: Icon, label, value, delta }: any) { return <div className="rounded-2xl border border-[#d8e4dc] bg-white p-4 shadow-[0_8px_18px_-18px_rgba(25,65,45,.55)]"><div className="mb-3 flex items-center gap-2 text-[12px] text-[#718579]"><span className="flex size-7 items-center justify-center rounded-full bg-[#e4f4ef] text-[#008f5a]"><Icon className="size-3.5" /></span>{label}</div><div className="text-[23px] font-semibold tracking-[-0.04em]">{value}</div><div className="mt-0.5 text-[11px] text-[#008f5a]">{delta}</div></div> }
function Stats() { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat icon={Utensils} label="Meals Rescued" value="24,680" delta="+1,240 this month" /><Stat icon={Leaf} label="Food Diverted" value="6,170 kg" delta="+310 kg this month" /><Stat icon={Truck} label="Successful Pickups" value="412" delta="18 this week" /><Stat icon={PackageCheck} label="Active Donors" value="86" delta="+7 new partners" /></div> }
function Dashboard({ onDonate }: { onDonate: () => void }) { return <div><Header title={<>Good afternoon <span aria-hidden="true">👋</span></>} subtitle="Let's rescue more food today." action={<button onClick={onDonate} className="flex items-center gap-2 rounded-xl bg-[#008f5a] px-5 py-2.5 text-[13px] font-semibold text-white shadow-sm"><Plus className="size-4" />Donate Food</button>} /><Stats /><section className="mt-8"><div className="mb-3 flex items-end justify-between"><div><h2 className="text-[19px] font-medium tracking-[-0.04em]">Urgent Food Opportunities</h2><p className="text-[13px] text-[#718579]">Sorted by time remaining before the food is no longer safe to serve.</p></div><button className="hidden items-center gap-2 text-[12px] font-medium sm:flex">See all <ArrowRight className="size-3.5" /></button></div><div className="grid gap-3 lg:grid-cols-3">{foods.slice(2, 5).map((item) => <FoodCard key={item.title} item={item} />)}</div></section><Activity /></div> }
function Activity() { return <section className="mt-8"><h2 className="mb-3 text-[19px] font-medium tracking-[-0.04em]">Recent Activity</h2><div className="overflow-hidden rounded-2xl border border-[#d8e4dc] bg-white">{activity.map(([text, time, color]) => <div key={text} className="flex items-center gap-3 border-b border-[#e4ebe6] px-4 py-3.5 last:border-0"><span className={`size-2 shrink-0 rounded-full ${color === 'green' ? 'bg-[#0a9961]' : 'bg-[#e99a21]'}`} /><span className="flex-1 text-[12px]">{text}</span><span className="text-[10px] text-[#718579]">{time}</span></div>)}</div></section> }
function FoodCard({ item, onClaim }: { item: any; onClaim?: () => void }) { return <article className={`rounded-2xl border bg-white p-4 shadow-[0_8px_18px_-16px_rgba(25,65,45,.55)] ${item.level === 'Critical' ? 'border-[#79ceb0]' : 'border-[#d8e4dc]'}`}><div className="flex items-start justify-between gap-2"><div><h3 className="text-[14px] font-semibold">{item.title}</h3><p className="mt-1 text-[11px] leading-4 text-[#718579]">{item.source}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-medium ${item.level === 'Critical' ? 'bg-[#fde7e7] text-[#e45151]' : item.level === 'Urgent' ? 'bg-[#fff0d8] text-[#9a6418]' : 'bg-[#e1f5ed] text-[#008f5a]'}`}>{item.level}</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-[12px]"><div><Users className="mb-1 size-3.5 text-[#008f5a]" />{item.servings}<small className="block text-[10px] text-[#718579]">servings</small></div><div><MapPin className="mb-1 size-3.5 text-[#008f5a]" />{item.distance}<small className="block text-[10px] text-[#718579]">away</small></div><div><Clock3 className="mb-1 size-3.5 text-[#14241b]" />{item.time}<small className="block text-[10px] text-[#718579]">to collect</small></div></div><div className="mt-4 flex items-center gap-3 rounded-full bg-[#e9f6f1] px-3 py-2 text-[12px]"><span className="text-[#008f5a]">✣</span>Rescue Score {item.score}<span className="ml-auto h-1.5 w-16 rounded-full bg-[#c7e6da]"><span className="block h-1.5 rounded-full bg-[#008f5a]" style={{ width: `${item.score}%` }} /></span></div><div className="mt-3 flex items-center justify-between text-[11px] text-[#718579]"><span>{item.category}</span><button onClick={onClaim} className="rounded-xl bg-[#e9f6f1] px-3 py-2 font-medium text-[#315946]">{onClaim ? 'Claim listing' : 'View Details'}</button></div></article> }
function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <div className={`rounded-2xl border border-[#d8e4dc] bg-white p-5 shadow-[0_8px_18px_-16px_rgba(25,65,45,.4)] ${className}`}>{children}</div> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="flex flex-col gap-1 text-[12px] font-medium">{label}{children}</label> }
const inputClass = 'w-full rounded-xl border border-[#d8e4dc] bg-white px-3 py-2.5 text-[12px] font-normal outline-none focus:border-[#008f5a] focus:ring-2 focus:ring-[#d9eee5]'
function DonateFood({ donation, setDonation, onAnalyze }: any) { const update = (key: string) => (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setDonation({ ...donation, [key]: e.target.value }); return <div><Header title="Donate Food" subtitle="Tell us what's left over. FoodLoop AI handles scoring, matching and the pickup window." /><div className="grid gap-5 lg:grid-cols-[1.35fr_.9fr]"><Card className="grid gap-4"><Field label="Food name"><input className={inputClass} value={donation.name} onChange={update('name')} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Quantity"><input className={inputClass} value={donation.quantity} onChange={update('quantity')} /></Field><Field label="Estimated servings"><input className={inputClass} value={donation.servings} onChange={update('servings')} /></Field></div><Field label="Food type"><select className={inputClass} value={donation.type} onChange={update('type')}><option>Vegetarian</option><option>Non-vegetarian</option><option>Vegan</option></select></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Prepared at"><input className={inputClass} value={donation.prepared} onChange={update('prepared')} /></Field><Field label="Available until"><input className={inputClass} value={donation.until} onChange={update('until')} /></Field></div><Field label="Pickup location"><input className={inputClass} value={donation.location} onChange={update('location')} /></Field><Field label="Notes for the recipient"><textarea className={`${inputClass} min-h-16 resize-y`} value={donation.notes} onChange={update('notes')} /></Field></Card><div className="flex flex-col gap-5"><Card><div className="mb-2 text-[12px] font-medium">Food photo</div><button onClick={() => onAnalyze()} className="flex h-32 w-full flex-col items-center justify-center gap-2 rounded-2xl border border-dashed border-[#c9ded3] bg-[#f4faf6] text-[12px] text-[#315946]"><ImagePlus className="text-[#008f5a]" />Add a photo<span className="text-[10px] text-[#718579]">Helps the AI judge portion size and freshness</span></button></Card><div className="rounded-2xl border border-[#9ed8c0] bg-[#e5f5ed] p-5"><p className="mb-4 text-[12px] leading-5 text-[#5b7566]">FoodLoop AI reviews freshness, urgency and demand nearby, then suggests the best recipient for this donation.</p><button onClick={onAnalyze} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#008f5a] px-4 py-2.5 text-[12px] font-semibold text-white"><Leaf className="size-3.5" />Analyze with FoodLoop AI</button></div></div></div></div> }
function AvailableFood({ search, setSearch, onClaim }: any) { const filtered = useMemo(() => foods.filter((item) => `${item.title} ${item.source}`.toLowerCase().includes(search.toLowerCase())), [search]); return <div><Header title="Available Food" subtitle="Surplus food listed by donors near your organisation, refreshed continuously." /><Card className="mb-7"><div className="grid gap-3 md:grid-cols-[1.5fr_1fr_1fr_1fr]"><Field label="Search"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-[#718579]" /><input className={`${inputClass} pl-9`} placeholder="Food, donor or area" value={search} onChange={(e) => setSearch(e.target.value)} /></div></Field><Field label="Food type"><select className={inputClass}><option>All types</option><option>Vegetarian</option><option>Vegan</option></select></Field><Field label="Distance"><select className={inputClass}><option>Any distance</option><option>Within 3 km</option></select></Field><Field label="Urgency"><select className={inputClass}><option>Any urgency</option><option>Critical</option></select></Field></div><div className="mt-4 flex items-center gap-2 text-[11px] text-[#718579]"><SlidersHorizontal className="size-3.5" />{filtered.length} listings match your filters</div></Card><div className="grid gap-3 lg:grid-cols-3">{filtered.map((item) => <FoodCard key={item.title} item={item} onClaim={onClaim} />)}</div></div> }
function Pickups({ tab, setTab, onConfirm }: any) { const rows = foods.slice(2, 4); return <div><Header title="Pickups" subtitle="Every rescue in motion, from first acceptance to meals served." /><div className="mb-7 inline-flex rounded-xl bg-[#eaf4ee] p-1 text-[12px]">{['Pending', 'Confirmed', 'Completed'].map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-3 py-1.5 ${tab === item ? 'bg-white shadow-sm' : 'text-[#61766a]'}`}>{item} <span className="ml-1">2</span></button>)}</div><div className="grid gap-3 lg:grid-cols-2">{rows.map((row) => <Card key={row.title}><div className="flex items-start justify-between"><div><h3 className="text-[14px] font-semibold">{row.title}</h3><p className="mt-1 text-[12px] text-[#718579]">{row.category}</p></div><span className="rounded-full bg-[#fff0d8] px-2 py-1 text-[10px] text-[#9a6418]">{tab}</span></div><div className="mt-4 grid gap-2 text-[12px] text-[#61766a]"><div className="flex justify-between"><span><Users className="mr-2 inline size-3.5 text-[#008f5a]" />Servings</span><b className="font-normal text-[#22362b]">{row.servings} meals</b></div><div className="flex justify-between"><span><PackageCheck className="mr-2 inline size-3.5 text-[#008f5a]" />Donor</span><b className="font-normal text-[#22362b]">{row.source.split(' �� ')[0]}</b></div><div className="flex justify-between"><span><CalendarDays className="mr-2 inline size-3.5 text-[#008f5a]" />Pickup window</span><b className="font-normal text-[#22362b]">Today, 4:00 – 5:00 pm</b></div></div>{tab !== 'Completed' && <button onClick={onConfirm} className="mt-4 rounded-xl bg-[#e9f6f1] px-3 py-2 text-[11px] font-medium text-[#315946]"><Check className="mr-1 inline size-3" />Confirm pickup</button>}</Card>)}</div></div> }
function Impact() { return <div><Header title="Impact Dashboard" subtitle="What the network has rescued so far this year." /><Stats /><Card className="mt-8"><h2 className="text-[16px] font-medium">Monthly trend</h2><p className="text-[12px] text-[#718579]">Meals rescued over the last six months.</p><div className="mt-4 h-[240px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ left: 0, right: 0, top: 10, bottom: 0 }}><defs><linearGradient id="impactFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#008f5a" stopOpacity={0.22} /><stop offset="100%" stopColor="#008f5a" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#dbe8e0" strokeDasharray="2 2" vertical={false} /><XAxis dataKey="month" tick={{ fontSize: 10, fill: '#718579' }} tickLine={false} axisLine={false} /><YAxis tick={{ fontSize: 10, fill: '#718579' }} tickLine={false} axisLine={false} domain={[0, 4000]} /><Tooltip /><Area type="monotone" dataKey="meals" stroke="#008f5a" strokeWidth={2} fill="url(#impactFill)" /></AreaChart></ResponsiveContainer></div></Card><Card className="mt-8"><h2 className="text-[16px] font-medium">Progress towards rescue goal</h2><p className="text-[12px] text-[#718579]">24,680 of 30,000 meals — 82% of the annual target.</p><div className="mt-4 h-2 rounded-full bg-[#c9e5d9]"><div className="h-2 w-[82%] rounded-full bg-[#008f5a]" /></div><div className="mt-2 flex justify-between text-[10px] text-[#718579]"><span>0</span><span>30,000 meals</span></div></Card><h2 className="mt-8 text-[16px] font-medium">Estimated environmental savings</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><Stat icon={Leaf} label="CO₂ avoided" value="12.4 t" delta="this year" /><Stat icon={Utensils} label="Water saved" value="2.8M L" delta="this year" /><Stat icon={PackageCheck} label="Waste diverted" value="6,170 kg" delta="this year" /></div></div> }
